import { formatDate, formatMoney } from "@/lib/format";
import type { AdminResource } from "@/types/admin";

const dateColumn = (name: string, label: string) => ({
  name,
  label,
  format: (value: unknown) => (value ? formatDate(String(value)) : "—"),
});

const boolColumn = (name: string, label: string) => ({
  name,
  label,
  format: (value: unknown) => (value ? "Evet" : "Hayır"),
});

const statusOptions = [
  { value: "active", label: "Aktif" },
  { value: "suspended", label: "Askıda" },
  { value: "pending", label: "Beklemede" },
  { value: "cancelled", label: "İptal" },
];

const contentStatusOptions = [
  { value: "draft", label: "Taslak" },
  { value: "published", label: "Yayında" },
  { value: "archived", label: "Arşiv" },
];

const localeField = {
  name: "locale",
  label: "Dil",
  type: "select" as const,
  required: true,
  optionsFrom: "languages" as const,
};

const sortField = { name: "sort_order", label: "Sıra", type: "number" as const };
const activeField = { name: "is_active", label: "Aktif", type: "boolean" as const };

/** Declarative definitions for every generic admin screen. */
export const adminResources = {
  users: {
    key: "users",
    title: "Kullanıcılar",
    description: "Platform kullanıcı profilleri. Kimlik doğrulama Supabase Auth üzerinden yürür.",
    table: "profiles",
    select: "id, email, full_name, locale, avatar_url, created_at",
    orderBy: "created_at",
    ascending: false,
    noDelete: true,
    searchColumns: ["email", "full_name"],
    columns: [
      { name: "email", label: "E-posta" },
      { name: "full_name", label: "Ad soyad" },
      { name: "locale", label: "Dil" },
      dateColumn("created_at", "Kayıt"),
    ],
    fields: [
      { name: "full_name", label: "Ad soyad", type: "text" },
      { ...localeField, required: false },
      { name: "avatar_url", label: "Avatar adresi", type: "text", full: true },
    ],
  },

  roles: {
    key: "roles",
    title: "Roller",
    description: "Sistem rolleri. Yetkilendirme veritabanı tarafında RLS ile zorunlu kılınır.",
    table: "roles",
    select: "id, key, name, description, is_system, sort_order",
    orderBy: "sort_order",
    noDelete: true,
    columns: [
      { name: "key", label: "Anahtar" },
      { name: "name", label: "Ad" },
      { name: "description", label: "Açıklama" },
      boolColumn("is_system", "Sistem"),
    ],
    fields: [
      { name: "name", label: "Ad", type: "text", required: true },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      sortField,
    ],
  },

  permissions: {
    key: "permissions",
    title: "Yetkiler",
    description: "Modül/aksiyon bazlı yetki tanımları; rollere bağlanarak kullanılır.",
    table: "permissions",
    select: "id, key, module, action, description",
    orderBy: "key",
    searchColumns: ["key", "module"],
    limit: 500,
    columns: [
      { name: "key", label: "Anahtar" },
      { name: "module", label: "Modül" },
      { name: "action", label: "Aksiyon" },
      { name: "description", label: "Açıklama" },
    ],
    fields: [
      { name: "key", label: "Anahtar", type: "text", required: true, placeholder: "menu.update" },
      { name: "module", label: "Modül", type: "text", required: true },
      { name: "action", label: "Aksiyon", type: "text", required: true },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
    ],
  },

  agents: {
    key: "agents",
    title: "Acenteler",
    description: "Acenteler kendilerine bağlı markaları yönetir; kota planla sınırlanır.",
    table: "agents",
    select:
      "id, name, slug, contact_email, contact_phone, tenant_quota, plan_id, status, created_at",
    orderBy: "created_at",
    ascending: false,
    softDelete: true,
    searchColumns: ["name", "slug", "contact_email"],
    columns: [
      { name: "name", label: "Acente" },
      { name: "slug", label: "Slug" },
      { name: "contact_email", label: "E-posta" },
      { name: "tenant_quota", label: "Marka kotası" },
      { name: "status", label: "Durum" },
    ],
    fields: [
      { name: "name", label: "Acente adı", type: "text", required: true },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        slugFrom: "name",
        help: "Boş bırakılırsa addan üretilir.",
      },
      { name: "contact_email", label: "E-posta", type: "text" },
      { name: "contact_phone", label: "Telefon", type: "text" },
      { name: "tenant_quota", label: "Marka kotası", type: "number" },
      { name: "plan_id", label: "Acente planı", type: "select", optionsFrom: "plans" },
      { name: "status", label: "Durum", type: "select", options: statusOptions },
    ],
  },

  announcements: {
    key: "announcements",
    title: "Topbar duyuruları",
    description: "Satış sitesinin üst bandında görünen duyurular.",
    table: "announcements",
    select: "id, locale, message, link_label, link_href, is_active, created_at",
    orderBy: "created_at",
    ascending: false,
    columns: [
      { name: "locale", label: "Dil" },
      { name: "message", label: "Mesaj" },
      { name: "link_label", label: "Bağlantı" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      localeField,
      { name: "message", label: "Mesaj", type: "textarea", required: true, full: true },
      { name: "link_label", label: "Bağlantı metni", type: "text" },
      { name: "link_href", label: "Bağlantı adresi", type: "text" },
      activeField,
    ],
  },

  landingSections: {
    key: "landing-sections",
    title: "Satış sayfası bölümleri",
    description: "Landing page bölümlerinin başlık, metin ve yapılandırmaları.",
    table: "landing_sections",
    select:
      "id, locale, key, eyebrow, title, subtitle, body, media_url, config, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["key", "title"],
    columns: [
      { name: "key", label: "Anahtar" },
      { name: "locale", label: "Dil" },
      { name: "title", label: "Başlık" },
      { name: "sort_order", label: "Sıra" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      localeField,
      {
        name: "key",
        label: "Bölüm anahtarı",
        type: "text",
        required: true,
        help: "Kullanılan anahtarlar: about, awards, specials, campaigns, posts, branches, contact",
      },
      { name: "eyebrow", label: "Üst etiket", type: "text" },
      { name: "title", label: "Başlık", type: "text" },
      { name: "subtitle", label: "Alt başlık", type: "text" },
      { name: "body", label: "Metin", type: "textarea", full: true },
      { name: "media_url", label: "Görsel adresi", type: "text", full: true },
      { name: "config", label: "Yapılandırma (JSON)", type: "json", full: true },
      sortField,
      activeField,
    ],
  },

  landingFeatures: {
    key: "landing-features",
    title: "Özellikler",
    description: "Satış sayfasında listelenen platform özellikleri.",
    table: "landing_features",
    select: "id, locale, section_key, icon, title, description, detail_html, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["title", "section_key"],
    columns: [
      { name: "title", label: "Başlık" },
      { name: "section_key", label: "Bölüm" },
      { name: "locale", label: "Dil" },
      { name: "sort_order", label: "Sıra" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      localeField,
      { name: "section_key", label: "Bölüm anahtarı", type: "text", required: true },
      { name: "icon", label: "İkon", type: "text" },
      { name: "title", label: "Başlık", type: "text", required: true },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "detail_html", label: "Detay (HTML)", type: "textarea", full: true },
      sortField,
      activeField,
    ],
  },

  faqs: {
    key: "faqs",
    title: "SSS",
    description: "Sık sorulan sorular ve yanıtları.",
    table: "landing_faqs",
    select: "id, locale, question, answer, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["question"],
    columns: [
      { name: "question", label: "Soru" },
      { name: "locale", label: "Dil" },
      { name: "sort_order", label: "Sıra" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      localeField,
      { name: "question", label: "Soru", type: "text", required: true, full: true },
      { name: "answer", label: "Yanıt", type: "textarea", required: true, full: true },
      sortField,
      activeField,
    ],
  },

  languages: {
    key: "languages",
    title: "Diller",
    description: "Platform dilleri; varsayılan dil tenant bazında ayrıca seçilir.",
    table: "languages",
    primaryKey: "code",
    select: "code, name, native_name, flag, is_active, is_default, sort_order",
    orderBy: "sort_order",
    columns: [
      { name: "code", label: "Kod" },
      { name: "name", label: "Ad" },
      { name: "native_name", label: "Yerel ad" },
      boolColumn("is_active", "Aktif"),
      boolColumn("is_default", "Varsayılan"),
    ],
    fields: [
      { name: "code", label: "Kod", type: "text", required: true, placeholder: "tr" },
      { name: "name", label: "Ad", type: "text", required: true },
      { name: "native_name", label: "Yerel ad", type: "text", required: true },
      { name: "flag", label: "Bayrak", type: "text" },
      activeField,
      { name: "is_default", label: "Varsayılan", type: "boolean" },
      sortField,
    ],
  },

  translations: {
    key: "translations",
    title: "Çeviriler",
    description: "Arayüz metinlerinin dil/namespace bazlı çevirileri.",
    table: "translations",
    select: "id, locale, namespace, key, value",
    orderBy: "key",
    searchColumns: ["key", "value", "namespace"],
    limit: 500,
    columns: [
      { name: "locale", label: "Dil" },
      { name: "namespace", label: "Namespace" },
      { name: "key", label: "Anahtar" },
      { name: "value", label: "Değer" },
    ],
    fields: [
      localeField,
      {
        name: "namespace",
        label: "Namespace",
        type: "text",
        required: true,
        placeholder: "common",
      },
      { name: "key", label: "Anahtar", type: "text", required: true },
      { name: "value", label: "Değer", type: "textarea", required: true, full: true },
    ],
  },

  siteSections: {
    key: "site-sections",
    title: "Website bölümleri",
    description: "Marka websitesindeki bölüm içerikleri.",
    table: "site_sections",
    tenantScoped: true,
    select: "id, key, eyebrow, title, subtitle, body, config, sort_order, is_active",
    orderBy: "sort_order",
    columns: [
      { name: "key", label: "Anahtar" },
      { name: "title", label: "Başlık" },
      { name: "sort_order", label: "Sıra" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      {
        name: "key",
        label: "Bölüm anahtarı",
        type: "text",
        required: true,
        help: "Kullanılan anahtarlar: about, awards, specials, campaigns, posts, branches, contact",
      },
      { name: "eyebrow", label: "Üst etiket", type: "text" },
      { name: "title", label: "Başlık", type: "text" },
      { name: "subtitle", label: "Alt başlık", type: "text" },
      { name: "body", label: "Metin", type: "textarea", full: true },
      { name: "config", label: "Yapılandırma (JSON)", type: "json", full: true },
      sortField,
      activeField,
    ],
  },

  siteNavigation: {
    key: "site-navigation",
    title: "Website menüsü",
    description: "Marka sitesinin üst menü bağlantıları.",
    table: "site_navigation",
    tenantScoped: true,
    select: "id, label, href, target, sort_order, is_active",
    orderBy: "sort_order",
    columns: [
      { name: "label", label: "Etiket" },
      { name: "href", label: "Adres" },
      { name: "target", label: "Hedef" },
      { name: "sort_order", label: "Sıra" },
    ],
    fields: [
      { name: "label", label: "Etiket", type: "text", required: true },
      { name: "href", label: "Adres", type: "text", required: true },
      {
        name: "target",
        label: "Hedef",
        type: "select",
        options: [
          { value: "_self", label: "Aynı sekme" },
          { value: "_blank", label: "Yeni sekme" },
        ],
      },
      sortField,
      activeField,
    ],
  },

  slides: {
    key: "slides",
    title: "Slider",
    description: "Marka sitesi ana görsel alanı.",
    table: "slides",
    tenantScoped: true,
    select:
      "id, image_url, eyebrow, title, description, button_label, button_href, button_target, sort_order, is_active",
    orderBy: "sort_order",
    columns: [
      { name: "title", label: "Başlık" },
      { name: "button_label", label: "Buton" },
      { name: "sort_order", label: "Sıra" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      { name: "image_url", label: "Görsel adresi", type: "text", full: true },
      { name: "eyebrow", label: "Üst etiket", type: "text" },
      { name: "title", label: "Başlık", type: "text" },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "button_label", label: "Buton metni", type: "text" },
      { name: "button_href", label: "Buton adresi", type: "text" },
      {
        name: "button_target",
        label: "Buton hedefi",
        type: "select",
        options: [
          { value: "_self", label: "Aynı pencere" },
          { value: "_blank", label: "Yeni pencere" },
        ],
      },
      sortField,
      activeField,
    ],
  },

  menus: {
    key: "menus",
    title: "Menüler",
    description: "Menü kayıtları; plan limiti veritabanı tarafında zorunlu kılınır.",
    table: "menus",
    tenantScoped: true,
    softDelete: true,
    publishable: true,
    select:
      "id, name, slug, category_id, price, currency, short_description, is_special, status, sort_order",
    orderBy: "sort_order",
    searchColumns: ["name"],
    columns: [
      { name: "name", label: "Menü" },
      {
        name: "price",
        label: "Fiyat",
        format: (value, row) => formatMoney(Number(value ?? 0), String(row["currency"] ?? "TRY")),
      },
      { name: "status", label: "Durum" },
      boolColumn("is_special", "Öne çıkan"),
    ],
    fields: [
      { name: "name", label: "Menü adı", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "name" },
      { name: "category_id", label: "Kategori", type: "select", optionsFrom: "menuCategories" },
      { name: "price", label: "Fiyat", type: "number", required: true },
      { name: "currency", label: "Para birimi", type: "text", placeholder: "TRY" },
      { name: "short_description", label: "Kısa açıklama", type: "textarea", full: true },
      { name: "is_special", label: "Öne çıkan", type: "boolean" },
      { name: "status", label: "Durum", type: "select", options: contentStatusOptions },
      sortField,
    ],
  },

  categories: {
    key: "categories",
    title: "Kategoriler",
    description: "Ürün ve menü kategorileri.",
    table: "menu_categories",
    tenantScoped: true,
    select: "id, name, slug, description, image_url, color, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["name"],
    columns: [
      { name: "name", label: "Kategori" },
      { name: "slug", label: "Slug" },
      { name: "sort_order", label: "Sıra" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      { name: "name", label: "Kategori adı", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "name" },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "image_url", label: "Görsel adresi", type: "text", full: true },
      { name: "color", label: "Renk", type: "text" },
      sortField,
      activeField,
    ],
  },

  branches: {
    key: "branches",
    title: "Şubeler",
    description: "Marka şubeleri; QR menü bağlantıları şube bazlı çalışır.",
    table: "branches",
    tenantScoped: true,
    softDelete: true,
    select:
      "id, name, slug, address, city, phone, whatsapp, directions_url, map_embed_url, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["name", "city"],
    columns: [
      { name: "name", label: "Şube" },
      { name: "city", label: "Şehir" },
      { name: "phone", label: "Telefon" },
      boolColumn("is_active", "Aktif"),
    ],
    fields: [
      { name: "name", label: "Şube adı", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "name" },
      { name: "address", label: "Adres", type: "textarea", full: true },
      { name: "city", label: "Şehir", type: "text" },
      { name: "phone", label: "Telefon", type: "text" },
      { name: "whatsapp", label: "WhatsApp", type: "text" },
      { name: "directions_url", label: "Yol tarifi adresi", type: "text", full: true },
      { name: "map_embed_url", label: "Harita gömme adresi", type: "text", full: true },
      sortField,
      activeField,
    ],
  },

  campaigns: {
    key: "campaigns",
    title: "Kampanyalar",
    description: "Marka kampanyaları ve duyurulan fırsatlar.",
    table: "campaigns",
    tenantScoped: true,
    softDelete: true,
    publishable: true,
    select:
      "id, title, slug, excerpt, description, image_url, badge, category, starts_at, ends_at, status, sort_order",
    orderBy: "sort_order",
    searchColumns: ["title"],
    columns: [
      { name: "title", label: "Kampanya" },
      dateColumn("starts_at", "Başlangıç"),
      dateColumn("ends_at", "Bitiş"),
      { name: "status", label: "Durum" },
    ],
    fields: [
      { name: "title", label: "Başlık", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "title" },
      { name: "excerpt", label: "Özet", type: "textarea", full: true },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "image_url", label: "Görsel adresi", type: "text", full: true },
      { name: "badge", label: "Etiket", type: "text" },
      { name: "category", label: "Kategori", type: "text" },
      { name: "starts_at", label: "Başlangıç", type: "date" },
      { name: "ends_at", label: "Bitiş", type: "date" },
      { name: "status", label: "Durum", type: "select", options: contentStatusOptions },
      sortField,
    ],
  },

  posts: {
    key: "posts",
    title: "Haberler",
    description: "Marka haber ve blog içerikleri.",
    table: "posts",
    tenantScoped: true,
    softDelete: true,
    publishable: true,
    select: "id, title, slug, excerpt, content, image_url, badge, status, published_at, view_count",
    orderBy: "created_at",
    ascending: false,
    searchColumns: ["title"],
    columns: [
      { name: "title", label: "Haber" },
      { name: "status", label: "Durum" },
      dateColumn("published_at", "Yayın"),
      { name: "view_count", label: "Görüntüleme" },
    ],
    fields: [
      { name: "title", label: "Başlık", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "title" },
      { name: "excerpt", label: "Özet", type: "textarea", full: true },
      { name: "content", label: "İçerik", type: "textarea", full: true },
      { name: "image_url", label: "Görsel adresi", type: "text", full: true },
      { name: "badge", label: "Etiket", type: "text" },
      { name: "status", label: "Durum", type: "select", options: contentStatusOptions },
      { name: "published_at", label: "Yayın tarihi", type: "date" },
    ],
  },

  media: {
    key: "media",
    title: "Medya",
    description: "Yüklenen dosyaların kayıtları ve alternatif metinleri.",
    table: "media",
    tenantScoped: true,
    select: "id, file_name, storage_path, mime_type, size_bytes, alt_text, created_at",
    orderBy: "created_at",
    ascending: false,
    searchColumns: ["file_name"],
    columns: [
      { name: "file_name", label: "Dosya" },
      { name: "mime_type", label: "Tür" },
      { name: "size_bytes", label: "Boyut" },
      dateColumn("created_at", "Tarih"),
    ],
    fields: [
      { name: "file_name", label: "Dosya adı", type: "text", required: true },
      { name: "storage_path", label: "Depolama yolu", type: "text", required: true, full: true },
      { name: "mime_type", label: "Tür", type: "text" },
      { name: "alt_text", label: "Alternatif metin", type: "text", full: true },
    ],
  },

  notifications: {
    key: "notifications",
    title: "Bildirimler",
    description: "Kullanıcılara gönderilen panel bildirimleri.",
    table: "notifications",
    select: "id, user_id, title, body, href, is_read, created_at",
    orderBy: "created_at",
    ascending: false,
    columns: [
      { name: "title", label: "Başlık" },
      { name: "body", label: "İçerik" },
      boolColumn("is_read", "Okundu"),
      dateColumn("created_at", "Tarih"),
    ],
    fields: [
      {
        name: "user_id",
        label: "Kullanıcı",
        type: "select",
        required: true,
        optionsFrom: "profiles",
      },
      { name: "title", label: "Başlık", type: "text", required: true },
      { name: "body", label: "İçerik", type: "textarea", full: true },
      { name: "href", label: "Bağlantı", type: "text", full: true },
    ],
  },

  systemSettings: {
    key: "system-settings",
    title: "Sistem ayarları",
    description: "Platform genelindeki anahtar/değer ayarları.",
    table: "system_settings",
    primaryKey: "key",
    select: "key, value, is_public, updated_at",
    orderBy: "key",
    searchColumns: ["key"],
    columns: [
      { name: "key", label: "Anahtar" },
      { name: "value", label: "Değer" },
      boolColumn("is_public", "Herkese açık"),
      dateColumn("updated_at", "Güncelleme"),
    ],
    fields: [
      { name: "key", label: "Anahtar", type: "text", required: true },
      { name: "value", label: "Değer (JSON)", type: "json", required: true, full: true },
      { name: "is_public", label: "Herkese açık", type: "boolean" },
    ],
  },

  auditLogs: {
    key: "audit-logs",
    title: "Audit log",
    description: "Kritik işlemlerin denetim kayıtları (salt okunur).",
    table: "audit_logs",
    readOnly: true,
    select: "id, module, action, record_id, tenant_id, actor_id, created_at",
    orderBy: "created_at",
    ascending: false,
    searchColumns: ["module", "action"],
    columns: [
      dateColumn("created_at", "Tarih"),
      { name: "module", label: "Modül" },
      { name: "action", label: "Aksiyon" },
      { name: "record_id", label: "Kayıt" },
      { name: "tenant_id", label: "Marka" },
    ],
    fields: [],
  },

  systemLogs: {
    key: "system-logs",
    title: "Sistem logları",
    description: "Sistem modülüne ait denetim kayıtları (salt okunur).",
    table: "audit_logs",
    readOnly: true,
    filter: { module: "system" },
    select: "id, module, action, record_id, context, created_at",
    orderBy: "created_at",
    ascending: false,
    columns: [
      dateColumn("created_at", "Tarih"),
      { name: "action", label: "Aksiyon" },
      { name: "record_id", label: "Kayıt" },
      { name: "context", label: "Bağlam" },
    ],
    fields: [],
  },

  products: {
    key: "products",
    title: "Ürünler",
    description: "Marka ürünleri; plan ürün limiti veritabanı tarafında zorunlu kılınır.",
    table: "products",
    tenantScoped: true,
    softDelete: true,
    publishable: true,
    select:
      "id, name, slug, category_id, price, currency, short_description, is_special, status, sort_order",
    orderBy: "sort_order",
    searchColumns: ["name"],
    columns: [
      { name: "name", label: "Ürün" },
      {
        name: "price",
        label: "Fiyat",
        format: (value, row) => formatMoney(Number(value ?? 0), String(row["currency"] ?? "TRY")),
      },
      { name: "status", label: "Durum" },
      boolColumn("is_special", "Öne çıkan"),
    ],
    fields: [
      { name: "name", label: "Ürün adı", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "name" },
      { name: "category_id", label: "Kategori", type: "select", optionsFrom: "menuCategories" },
      { name: "price", label: "Fiyat", type: "number", required: true },
      { name: "currency", label: "Para birimi", type: "text", placeholder: "TRY" },
      { name: "short_description", label: "Kısa açıklama", type: "textarea", full: true },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "image_url", label: "Görsel adresi", type: "text", full: true },
      { name: "is_special", label: "Öne çıkan", type: "boolean" },
      { name: "status", label: "Durum", type: "select", options: contentStatusOptions },
      sortField,
    ],
  },

  brands: {
    key: "brands",
    title: "Marka / şirket bilgileri",
    description: "Markanın alt marka ve şirket kayıtları; şubeler bu kayıtlara bağlanabilir.",
    table: "brands",
    tenantScoped: true,
    softDelete: true,
    select: "id, name, slug, description, logo_url, cover_image_url, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["name"],
    columns: [
      { name: "name", label: "Marka" },
      { name: "slug", label: "Slug" },
      boolColumn("is_active", "Aktif"),
      { name: "sort_order", label: "Sıra" },
    ],
    fields: [
      { name: "name", label: "Marka adı", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", slugFrom: "name" },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "logo_url", label: "Logo adresi", type: "text", full: true },
      { name: "cover_image_url", label: "Kapak görseli", type: "text", full: true },
      sortField,
      activeField,
    ],
  },

  awards: {
    key: "awards",
    title: "Ödüller / rozetler",
    description: "Marka sitesinde gösterilen ödül ve rozetler.",
    table: "awards",
    tenantScoped: true,
    select: "id, title, description, icon, image_url, detail_html, sort_order, is_active",
    orderBy: "sort_order",
    searchColumns: ["title"],
    columns: [
      { name: "title", label: "Ödül" },
      { name: "icon", label: "İkon" },
      boolColumn("is_active", "Aktif"),
      { name: "sort_order", label: "Sıra" },
    ],
    fields: [
      { name: "title", label: "Başlık", type: "text", required: true },
      { name: "description", label: "Açıklama", type: "textarea", full: true },
      { name: "icon", label: "İkon", type: "text" },
      { name: "image_url", label: "Görsel adresi", type: "text" },
      { name: "detail_html", label: "Detay içeriği", type: "textarea", full: true },
      sortField,
      activeField,
    ],
  },

  galleries: {
    key: "galleries",
    title: "Galeriler",
    description: "Hakkımızda ve şube sayfalarında kullanılan görsel galerileri.",
    table: "galleries",
    tenantScoped: true,
    select: "id, name, items, sort_order, is_active",
    orderBy: "sort_order",
    columns: [
      { name: "name", label: "Galeri" },
      boolColumn("is_active", "Aktif"),
      { name: "sort_order", label: "Sıra" },
    ],
    fields: [
      { name: "name", label: "Galeri adı", type: "text", required: true },
      { name: "items", label: "Görseller (JSON)", type: "json", full: true },
      sortField,
      activeField,
    ],
  },

  localizedContent: {
    key: "localized-content",
    title: "Dil içerikleri",
    description: "Marka içeriklerinin dil bazlı çevirileri (alan bazında).",
    table: "localized_content",
    tenantScoped: true,
    select: "id, entity_table, entity_id, field, locale, value, updated_at",
    orderBy: "updated_at",
    ascending: false,
    searchColumns: ["entity_table", "field", "value"],
    columns: [
      { name: "entity_table", label: "Tablo" },
      { name: "field", label: "Alan" },
      { name: "locale", label: "Dil" },
      { name: "value", label: "Değer" },
    ],
    fields: [
      {
        name: "entity_table",
        label: "Tablo",
        type: "select",
        required: true,
        options: [
          { value: "products", label: "Ürünler" },
          { value: "menus", label: "Menüler" },
          { value: "menu_categories", label: "Kategoriler" },
          { value: "campaigns", label: "Kampanyalar" },
          { value: "posts", label: "Haberler" },
          { value: "site_sections", label: "Website bölümleri" },
          { value: "awards", label: "Ödüller" },
          { value: "branches", label: "Şubeler" },
        ],
      },
      { name: "entity_id", label: "Kayıt kimliği", type: "text", required: true, full: true },
      { name: "field", label: "Alan", type: "text", required: true, placeholder: "title" },
      { ...localeField },
      { name: "value", label: "Çeviri", type: "textarea", required: true, full: true },
    ],
  },

  tenantPlugins: {
    key: "tenantPlugins",
    title: "Eklentiler",
    description: "Markaya atanmış eklentiler; erişim plan ve yetkilerle sınırlıdır.",
    table: "plugin_assignments",
    tenantScoped: true,
    select: "id, plugin_id, is_enabled, settings, created_at",
    orderBy: "created_at",
    ascending: false,
    columns: [
      { name: "plugin_id", label: "Eklenti" },
      boolColumn("is_enabled", "Aktif"),
      dateColumn("created_at", "Tarih"),
    ],
    fields: [
      { name: "plugin_id", label: "Eklenti", type: "select", required: true, optionsFrom: "plugins" },
      { name: "is_enabled", label: "Aktif", type: "boolean" },
      { name: "settings", label: "Ayarlar (JSON)", type: "json", full: true },
    ],
  },
} satisfies Record<string, AdminResource>;


export type AdminResourceKey = keyof typeof adminResources;
